name: 'Continuous Delivery'

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build Docker image #
        run: |
          docker build --pull --rm -t ${{ secrets.IMAGE_NAME}}:latest .
      
      - name: Docker tag image
        run: docker tag ${{ secrets.IMAGE_NAME}}:latest ${{ secrets.REGISTRY_HOST}}/${{ secrets.PROJECT_ID}}/${{ secrets.ARTIFACT_REGISTRY}}/${{ secrets.IMAGE_NAME}}:latest
          
      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker ${{secrets.REGISTRY_HOST}} --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{secrets.REGISTRY_HOST}}/${{secrets.PROJECT_ID}}/${{secrets.ARTIFACT_REGISTRY}}/${{secrets.IMAGE_NAME}}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{secrets.CLOUD_RUN_SERVICE_NAME}} \
            --image ${{secrets.REGISTRY_HOST}}/${{secrets.PROJECT_ID}}/${{secrets.ARTIFACT_REGISTRY}}/${{secrets.IMAGE_NAME}}:latest \
            --region ${{secrets.REGION}} \
            --platform managed \
            --allow-unauthenticated
      
      - name: Run Stress Tests
        run: make stress-test
