name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t ${REGISTRY_HOST}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA} .

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker ${REGISTRY_HOST} --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${REGISTRY_HOST}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE_NAME} \
            --image ${REGISTRY_HOST}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated
      
      - name: Run Stress Tests
        run: make stress-test
