name: 'Continuous Delivery'

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          #service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate Docker to Artifact Registry
        run: |
          echo ${{ secrets.GCP_CREDENTIALS }} > $HOME/gcp-credentials.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-credentials.json

      - name: Build Docker image
        run: docker build --pull --rm -t ${{ secrets.IMAGE_NAME}}:latest .
      
      - name: Docker tag image
        run: docker tag ${{ secrets.IMAGE_NAME}}:latest ${{ secrets.REGISTRY_HOST}}/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.ARTIFACT_REGISTRY}}/${{ secrets.IMAGE_NAME}}:latest
          
      #- name: Authenticate Docker to Artifact Registry
      #  run: gcloud auth print-access-token \
      #        --impersonate-service-account github-actions@centered-carver-337623.iam.gserviceaccount.com | docker login \
      #        -u oauth2accesstoken \
      #        --password-stdin https://us-central1-docker.pkg.dev
        #gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
        #sudo gcloud auth configure-docker ${{secrets.REGISTRY_HOST}}/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.ARTIFACT_REGISTRY}}
          
      #- name: Authenticate Docker to Artifact Registry
      #  run: |
      #    gcloud auth configure-docker ${{secrets.REGISTRY_HOST}}/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.ARTIFACT_REGISTRY}}

      - name: Push Docker image to Artifact Registry #
        env: 
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID}}
        run:  docker push us-central1-docker.pkg.dev/centered-carver-337623/challengelatam/challengemle:latest
              #docker push ${{ secrets.REGISTRY_HOST}}/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.ARTIFACT_REGISTRY}}/${{ secrets.IMAGE_NAME}}:latest
              #docker push ${{secrets.REGISTRY_HOST}}/${{secrets.GCP_PROJECT_ID}}/${{secrets.ARTIFACT_REGISTRY}}/${{secrets.IMAGE_NAME}}:latest
              #docker push gcr.io/PROJECT_ID/MY_IMAGE:$GIT_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{secrets.CLOUD_RUN_SERVICE_NAME}} \
            --image ${{secrets.REGISTRY_HOST}}/${{secrets.GCP_PROJECT_ID}}/${{secrets.ARTIFACT_REGISTRY}}/${{secrets.IMAGE_NAME}}:latest \
            --region ${{secrets.REGION}} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=1Gi \
            --cpu=2 \
            --max-instances=10 \
            --min-instances=1 \
            --concurrency=10 \
            --timeout=60s
      
      - name: Run Stress Tests
        run: make stress-test
