name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt

      - name: Check formatting with Black
        run: |
          pip install black
          black --check .

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run Model Tests
        run: make model-test

      - name: Run API Tests
        run: make api-test

      - name: Run Stress Tests
        run: make stress-test

  build-docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (Validation)
        run: |
          docker build -t challengemle:latest .
